# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80
    connection-timeout: 5000ms


# mysql
spring:
    devtools:
      restart:
        enabled: true
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
#        multipart:
#            max-file-size: 100mb
#            max-request-size: 100MB
#            enabled: true
        encoding:
             charset: UTF-8
             enabled: true
             force: true
    data:
      cassandra:
        pool:
          max-queue-size:
    servlet:
      multipart:
        max-file-size: 100mb
        max-request-size: 100mb
        enabled: true
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: 120.78.197.187
        port: 6379
        password:       # 密码（默认为空）
        timeout: 60000ms  # 连接超时时长（毫秒）
        jedis:
          pool:
            max-active: 1000
            max-idle: 10
            min-idle: 5
            max-wait: -1ms
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis.xml

#上传文件路径
photo:
   drive: D:\
   full-path: D:\Users\Administrator\IdeaProject\exam\target\classes\static\studentResource\
   student-upload: studentResource\
   access-path: http://localhost:8081/static/studentResource/
   app-dir: Users\Administrator\IdeaProject\exam\src\main\resources\static\

file:
  drive: D:\
  full-path: D:\Users\Administrator\IdeaProject\exam\target\classes\static\fileResource\
  file-upload: fileResource\
  access-path: http://localhost:8081/static/fileResource/
  app-dir: Users\Administrator\IdeaProject\exam\src\main\resources\static\